# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - camel_case_types
    - non_constant_identifier_names
    - library_prefixes
    # - unused_import
    # - unused_shown_name
    # - return_of_invalid_type

analyzer:
#   exclude:
#     - path/to/excluded/files/**
