name: xuper_sdk
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pointycastle: ^1.0.1
  grpc: ^2.2.0
  protobuf: ^1.0.1
  fast_base58: ^0.1.8
  uuid: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
